.TH FLL-ISO2USB "8" "12th October 2007" "" ""
.SH NAME
\fBfll-iso2usb\fR \- installs a live-CD iso build with the
fll\-tools as a fromiso into a USB pen
.SH SYNOPSIS
\fBfll-iso2usb\fR \fI<options>\fR \fI-- <extra_options_to_grub>\fR
.SH DESCRIPTION
installs a \fBF.U.L.L.S.T.O.R.Y.\fR iso-image on a USB-pen, makes the pen
bootable and writes the needed grub files.
.PP
\fBfll-iso2usb\fR creates a partition over the USB-device, installs
grub and copies the iso into it. When running from the live CD it copies his
contents into the US device.
.PP
\fBfll-iso2usb\fR is intended to be called by the
\fBinstall-usb-gui\fR program but can also be called directly.
.PP
.SH OPTIONS
.TP
\fB\-h|\-\-help\fR
print help screen
.TP
\fB\-D|\-\-device\fR \fI<device>\fR
name of device where to install the \"fromiso\"
.TP
\fB\-I|\-\-iso\fR \fI<iso_file>\fR
name of the iso image to be installed
.TP
\fB\-L|\-\-label\fR \fI<name>\fR
label name to be used for the created partition
.TP
\fB\-t|\-\-test\fR
do not copy the iso image
.TP
\fB\-d|\-\-debug\fR
debug sh code execution
.PP
.SH EXAMPLES
.TP
\fBfll-iso2usb \-D /dev/sdb /home/sidux/sidux.iso \\\fR
\fB            \-\- toram lang=de tz=Europe/Berlin persist\fR
.PP
installs the iso image into the USB device sdb. Uses the cheatcodes on the 
grub default command line.
.PP
.SH AUTHOR
This manual page was written by Joaquim Boura <x-un-i@sidux.com>
