#!/bin/bash
#
# (Copyright  (C) 2007 sidux Foundation,Inc.
#             (C) 2007 Joaquim Boura <x-un-i@sidux.com>
# heavliy based on the knoppix installe from
#         Fabian Franz <knoppix-installer@fabian-franz.de>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this package; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
# MA 02110-1301, USA.
#
# On Debian GNU/Linux systems, the text of the GPL license can be
# found in /usr/share/common-licenses/GPL.
#
#--------------------------------------------------------------------------

#
# Include needed Bash-Modules
#

SEARCHPATH="/usr/share/fll-installer"
[ -f ./modules/initialization.bm  ] && SEARCHPATH="modules"

for i in $(find $SEARCHPATH -name "*.bm"); do
	source $i
done

#------------------

trap clean_exit EXIT

#------------------

if [ "$1" = "installer" ]; then
	test -n "$2" && INSTALLER_INOTIFY="$2"
	INSTALL_MODE=installer main
	exit 1 # something did go wrong
fi

# something did go wrong
exit 1 

#------------------

